version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: waterdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"   # localhost access only
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      POSTGRES_DB: waterdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:4000:4000"   # localhost access only
    depends_on:
      - db

  frontend:
    build: .
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "127.0.0.1:5173:5173"   # localhost access only
    depends_on:
      - backend

volumes:
  pgdata:
